(function(){
  var el = document.getElementById('rsa-providers-pa');
  if (!el) return;
  if (!document.getElementById('rsa-ix-styles')) {
    var s = document.createElement('style');
    s.id = 'rsa-ix-styles';
    s.textContent = `.rsa-ix-wrap { font-family: 'Onest', sans-serif; color: #0b1220; background: #f6f7fa; }
.rsa-ix-hero { background: linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%); color: white; padding: 48px 24px 40px; }
.rsa-ix-hero h1 { font-family: 'Onest', sans-serif; font-size: clamp(28px, 4vw, 40px); font-weight: 700; line-height: 1.2; margin: 12px 0 10px; letter-spacing: -0.5px; }
.rsa-ix-hero p { font-size: 17px; opacity: 0.88; max-width: 620px; line-height: 1.6; margin: 0; }
.rsa-ix-breadcrumb { font-size: 13px; opacity: 0.72; margin-bottom: 10px; }
.rsa-ix-breadcrumb a { color: white; text-decoration: none; }
.rsa-ix-breadcrumb a:hover { text-decoration: underline; }
.rsa-ix-breadcrumb span { margin: 0 5px; opacity: 0.6; }
.rsa-ix-bc-current { opacity: 0.9; }
.rsa-ix-content { max-width: 940px; margin: 0 auto; padding: 40px 24px 64px; }
.rsa-ix-stats { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 28px; }
.rsa-ix-stat { background: white; border: 1px solid #e9eaee; border-radius: 10px; padding: 14px 20px; box-shadow: 0 1px 3px rgba(11,18,32,0.06); }
.rsa-ix-stat .num { font-size: 1.75rem; font-weight: 700; line-height: 1; color: #1e3a5f; }
.rsa-ix-stat .lbl { font-size: 11px; color: #5a6578; margin-top: 3px; text-transform: uppercase; letter-spacing: 0.05em; }
.rsa-ix-intro { background: white; border-left: 3px solid #2563eb; border-radius: 0 10px 10px 0; padding: 14px 18px; margin-bottom: 28px; font-size: 14px; line-height: 1.7; color: #2a3446; box-shadow: 0 1px 3px rgba(11,18,32,0.06); }
.rsa-ix-section-label { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #5a6578; margin-bottom: 12px; }
.rsa-ix-carrier-nav { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 24px; background: white; padding: 12px 16px; border-radius: 10px; border: 1px solid #e9eaee; }
.rsa-ix-carrier-nav a { display: inline-block; padding: 4px 10px; border-radius: 6px; background: #f6f7fa; color: #2a3446; font-size: 12px; font-weight: 600; text-decoration: none; border: 1px solid #e9eaee; transition: all 0.12s; }
.rsa-ix-carrier-nav a:hover { background: #1e3a5f; color: white; border-color: #1e3a5f; }
.rsa-ix-card { background: white; border: 1px solid #e9eaee; border-radius: 10px; box-shadow: 0 1px 3px rgba(11,18,32,0.06); margin-bottom: 16px; overflow: hidden; }
.rsa-ix-card-header { padding: 14px 20px; border-bottom: 1px solid #eef0f5; display: flex; align-items: center; gap: 10px; border-left: 3px solid #2563eb; }
.rsa-ix-card-header .name { font-weight: 700; font-size: 15px; color: #0b1220; }
.rsa-ix-card-header .link { font-size: 12px; color: #2563eb; text-decoration: none; margin-left: 6px; }
.rsa-ix-card-header .link:hover { text-decoration: underline; }
.rsa-ix-card-header .count { margin-left: auto; font-size: 11px; background: #f6f7fa; color: #5a6578; padding: 2px 8px; border-radius: 999px; font-weight: 600; border: 1px solid #e9eaee; }
.rsa-ix-list { list-style: none; margin: 0; padding: 0; }
.rsa-ix-list li a { display: flex; align-items: center; gap: 10px; padding: 10px 20px; text-decoration: none; color: #0b1220; font-size: 14px; border-bottom: 1px solid #f6f7fa; transition: background 0.1s; }
.rsa-ix-list li:last-child a { border-bottom: none; }
.rsa-ix-list li a:hover { background: #f6f7fa; }
.rsa-ix-list li a .item-name { flex: 1; color: #2563eb; font-weight: 500; }
.rsa-ix-list li a:hover .item-name { color: #1d4ed8; }
.rsa-ix-list li a .badge { font-size: 11px; font-weight: 600; padding: 2px 7px; border-radius: 5px; background: #eef0f5; color: #2a3446; flex-shrink: 0; white-space: nowrap; }
.rsa-ix-list li a .badge.snp { background: #f9e9e9; color: #c62828; }
.rsa-ix-list li a .badge.pdp { background: #fef0d4; color: #6f4a03; }
.rsa-ix-list li a .badge.hmo { background: #e7f2ee; color: #1e5a45; }
.rsa-ix-list li a .badge.ppo { background: #eff6ff; color: #1d4ed8; }
.rsa-ix-alpha { margin-bottom: 8px; }
.rsa-ix-alpha-letter { font-size: 13px; font-weight: 700; color: #1e3a5f; background: #eef0f5; padding: 6px 20px; border-left: 3px solid #2563eb; margin: 0; }
.rsa-ix-alpha-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0; }
.rsa-ix-alpha-grid a { display: block; padding: 9px 20px; font-size: 13px; color: #2563eb; text-decoration: none; border-bottom: 1px solid #f6f7fa; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.rsa-ix-alpha-grid a:hover { background: #f6f7fa; color: #1d4ed8; }
@media(max-width: 640px) { .rsa-ix-alpha-grid { grid-template-columns: repeat(2,1fr); } }
.rsa-ix-state-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px; }
@media(max-width: 700px) { .rsa-ix-state-grid { grid-template-columns: 1fr; } }
.rsa-ix-state-card { background: white; border: 1px solid #e9eaee; border-radius: 10px; padding: 24px; box-shadow: 0 1px 3px rgba(11,18,32,0.06); }
.rsa-ix-state-card h2 { font-size: 20px; font-weight: 700; color: #0b1220; margin: 0 0 4px; }
.rsa-ix-state-card .count { font-size: 13px; color: #5a6578; margin-bottom: 16px; }
.rsa-ix-state-card a.btn { display: inline-block; background: #2563eb; color: white; text-decoration: none; padding: 9px 16px; border-radius: 8px; font-size: 14px; font-weight: 600; }
.rsa-ix-state-card a.btn:hover { background: #1d4ed8; }
.rsa-ix-topic-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 32px; }
@media(max-width: 640px) { .rsa-ix-topic-grid { grid-template-columns: 1fr; } }
.rsa-ix-topic-card { background: white; border: 1px solid #e9eaee; border-radius: 10px; padding: 20px 24px; box-shadow: 0 1px 3px rgba(11,18,32,0.06); }
.rsa-ix-topic-card h2 { font-size: 16px; font-weight: 700; color: #0b1220; margin: 0 0 4px; }
.rsa-ix-topic-card .count { font-size: 12px; color: #5a6578; margin-bottom: 12px; }
.rsa-ix-topic-card a.btn { font-size: 13px; color: #2563eb; text-decoration: none; font-weight: 600; }
.rsa-ix-topic-card a.btn:hover { text-decoration: underline; }
.rsa-ix-qa-list { list-style: none; margin: 0; padding: 0; }
.rsa-ix-qa-list li { border-bottom: 1px solid #e9eaee; }
.rsa-ix-qa-list li:last-child { border-bottom: none; }
.rsa-ix-qa-list li a { display: block; padding: 13px 0; font-size: 15px; color: #2563eb; text-decoration: none; line-height: 1.5; font-weight: 500; }
.rsa-ix-qa-list li a:hover { color: #1d4ed8; }
.rsa-ix-qa-list li a::before { content: "Q: "; color: #5a6578; font-weight: 400; font-size: 13px; }
.rsa-ix-geo-section { margin-bottom: 24px; }
.rsa-ix-geo-section h2 { font-size: 16px; font-weight: 700; color: #1e3a5f; padding: 8px 16px; background: #eef0f5; border-radius: 8px; margin: 0 0 8px; }
.rsa-ix-geo-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0; background: white; border: 1px solid #e9eaee; border-radius: 10px; overflow: hidden; }
.rsa-ix-geo-grid a { display: block; padding: 9px 14px; font-size: 13px; color: #2563eb; text-decoration: none; border-bottom: 1px solid #f6f7fa; font-weight: 500; }
.rsa-ix-geo-grid a:hover { background: #f6f7fa; color: #1d4ed8; }
@media(max-width: 640px) { .rsa-ix-geo-grid { grid-template-columns: repeat(2,1fr); } }
.rsa-ix-related { display: flex; gap: 8px; flex-wrap: wrap; padding-top: 24px; border-top: 1px solid #e9eaee; margin-top: 32px; }
.rsa-ix-related a { padding: 7px 14px; border: 1px solid #e9eaee; border-radius: 8px; font-size: 13px; color: #2a3446; text-decoration: none; background: white; font-weight: 500; }
.rsa-ix-related a:hover { border-color: #2563eb; color: #2563eb; }
.rsa-ix-cluster { margin-bottom: 32px; }
.rsa-ix-cluster-header { font-size: 18px; font-weight: 700; color: #0b1220; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 2px solid #eef0f5; }
.rsa-ix-cluster-hub a { display: block; padding: 10px 16px; background: #eff6ff; border-radius: 8px; color: #1d4ed8; text-decoration: none; font-weight: 600; font-size: 15px; margin-bottom: 6px; border: 1px solid #dbeafe; }
.rsa-ix-cluster-hub a:hover { background: #dbeafe; }
.rsa-ix-cluster-spokes { list-style: none; padding: 0; margin: 0; }
.rsa-ix-cluster-spokes li a { display: block; padding: 8px 16px 8px 28px; font-size: 14px; color: #2563eb; text-decoration: none; border-bottom: 1px solid #f6f7fa; }
.rsa-ix-cluster-spokes li a::before { content: "↳ "; color: #5a6578; }
.rsa-ix-cluster-spokes li a:hover { color: #1d4ed8; background: #f6f7fa; }
.rsa-ix-specialty-table { width: 100%; border-collapse: collapse; background: white; border-radius: 10px; overflow: hidden; border: 1px solid #e9eaee; font-size: 14px; }
.rsa-ix-specialty-table th { background: #1e3a5f; color: white; padding: 10px 16px; text-align: left; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
.rsa-ix-specialty-table td { padding: 10px 16px; border-bottom: 1px solid #f6f7fa; }
.rsa-ix-specialty-table tr:last-child td { border-bottom: none; }
.rsa-ix-specialty-table tr:hover td { background: #f6f7fa; }
.rsa-ix-specialty-table a { color: #2563eb; text-decoration: none; font-weight: 500; }
.rsa-ix-specialty-table a:hover { text-decoration: underline; }
.rsa-ix-carrier-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 32px; }
@media(max-width: 640px) { .rsa-ix-carrier-grid { grid-template-columns: 1fr; } }
.rsa-ix-carrier-card { background: white; border: 1px solid #e9eaee; border-radius: 10px; padding: 16px 20px; box-shadow: 0 1px 3px rgba(11,18,32,0.06); }
.rsa-ix-carrier-card .carrier-name { font-size: 15px; font-weight: 700; color: #0b1220; margin-bottom: 4px; }
.rsa-ix-carrier-card .carrier-meta { font-size: 12px; color: #5a6578; margin-bottom: 12px; }
.rsa-ix-carrier-card a { font-size: 13px; color: #2563eb; text-decoration: none; font-weight: 600; }
.rsa-ix-carrier-card a:hover { text-decoration: underline; }
.rsa-ix-plantype-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; }
@media(max-width: 640px) { .rsa-ix-plantype-grid { grid-template-columns: 1fr; } }
.rsa-ix-plantype-card { background: white; border: 1px solid #e9eaee; border-radius: 10px; padding: 20px 24px; box-shadow: 0 1px 3px rgba(11,18,32,0.06); }
.rsa-ix-plantype-card h2 { font-size: 17px; font-weight: 700; color: #0b1220; margin: 0 0 8px; }
.rsa-ix-plantype-card p { font-size: 14px; color: #5a6578; line-height: 1.6; margin-bottom: 12px; }
.rsa-ix-plantype-card a { font-size: 13px; color: #2563eb; text-decoration: none; font-weight: 600; }`;
    document.head.appendChild(s);
  }
  el.innerHTML = `<div class="rsa-ix-wrap"><div class="rsa-ix-hero"><div class="rsa-ix-breadcrumb"><a href="https://www.restingsycamore.com">Home</a> <span>›</span> <a href="https://www.restingsycamore.com/medicare">Medicare</a> <span>›</span> <a href="https://www.restingsycamore.com/medicare/providers">Providers</a> <span>›</span> <span class="rsa-ix-bc-current">Pennsylvania</span></div><h1>Medicare Care Facilities in Pennsylvania</h1><p>167 Medicare-certified skilled nursing and care facilities in Pennsylvania.</p></div><div class="rsa-ix-content">
  <div class="rsa-ix-stats">
    <div class="rsa-ix-stat"><div class="num">167</div><div class="lbl">Facilities</div></div>
  </div>

  <div class="rsa-ix-intro">
    Medicare Part A covers up to 100 days in a skilled nursing facility after a qualifying hospital stay —
    but only at Medicare-certified facilities. These 167 Pennsylvania facilities are Medicare-certified.
    Click any facility to view coverage details, accepted plans, and location information.
  </div>

  <div class="rsa-ix-section-title">All Pennsylvania Medicare Care Facilities — A to Z</div>
  
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">A</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/abbeyville-skilled-nursing-and-rehabilitation-cent-provider-pa">Abbeyville Skilled Nursing And Rehabilitation Cent</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/accela-rehab-and-care-center-at-somerton-provider-pa">Accela Rehab And Care Center At Somerton</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/advanced-health-care-of-hanover-provider-pa">Advanced Health Care Of Hanover</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/allied-services-skilled-nursing-center-provider-pa">Allied Services Skilled Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/allied-services-transitional-rehab-unit-provider-pa">Allied Services Transitional Rehab Unit</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/amoroso-healthcare-and-rehabilitation-woodridge-provider-pa">Amoroso Healthcare And Rehabilitation Woodridge</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/aristacare-at-east-falls-provider-pa">Aristacare At East Falls</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/asbury-health-center-provider-pa">Asbury Health Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">B</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/ball-pavilion-the-provider-pa">Ball Pavilion The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/belvedere-center-genesis-healthcare-the-provider-pa">Belvedere Center Genesis Healthcare The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/bethlehem-north-skilled-nursing-and-rehabilitation-provider-pa">Bethlehem North Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/bethlehem-south-skilled-nursing-and-rehabilitation-provider-pa">Bethlehem South Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/brethren-village-provider-pa">Brethren Village</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/burgh-care-center-provider-pa">Burgh Care Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">C</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/canterbury-place-provider-pa">Canterbury Place</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/capitol-rehabilitation-and-healthcare-center-provider-pa">Capitol Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/care-pavilion-nursing-and-rehabilitation-center-provider-pa">Care Pavilion Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/caring-heart-rehabilitation-and-nursing-center-provider-pa">Caring Heart Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/carnegie-park-post-acute-provider-pa">Carnegie Park Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cathedral-village-provider-pa">Cathedral Village</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cedar-crest-post-acute-provider-pa">Cedar Crest Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cedarbrook-senior-care-and-rehabilitation-provider-pa">Cedarbrook Senior Care And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/centennial-healthcare-and-rehabilitation-center-provider-pa">Centennial Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/chapel-manor-provider-pa">Chapel Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cliveden-nursing-and-rehabilitation-center-provider-pa">Cliveden Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/complete-care-at-berkshire-llc-provider-pa">Complete Care At Berkshire Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/concordia-at-the-cedars-provider-pa">Concordia At The Cedars</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/concordia-of-the-south-hills-provider-pa">Concordia Of The South Hills</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/corner-view-nursing-and-rehabilitation-center-provider-pa">Corner View Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/country-meadows-nursing-center-of-bethlehem-provider-pa">Country Meadows Nursing Center Of Bethlehem</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">D</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/deer-meadows-rehabilitation-center-provider-pa">Deer Meadows Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/delaware-valley-veterans-home-provider-pa">Delaware Valley Veterans Home</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">E</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/east-end-health-rehab-center-provider-pa">East End Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/easton-skilled-nursing-and-rehabilitation-center-provider-pa">Easton Skilled Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/edenbrook-north-provider-pa">Edenbrook North</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/edenbrook-south-provider-pa">Edenbrook South</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/elan-skilled-nursing-and-rehab-a-jewish-senior-li-provider-pa">Elan Skilled Nursing And Rehab A Jewish Senior Li</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/embassy-of-east-mountain-provider-pa">Embassy Of East Mountain</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/embassy-of-hearthside-provider-pa">Embassy Of Hearthside</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/embassy-of-scranton-provider-pa">Embassy Of Scranton</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">F</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/fairlane-gardens-nursing-and-rehab-at-reading-provider-pa">Fairlane Gardens Nursing And Rehab At Reading</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/fairview-rehab-and-care-center-provider-pa">Fairview Rehab And Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/forestview-provider-pa">Forestview</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/fox-subacute-at-south-philadelphia-provider-pa">Fox Subacute At South Philadelphia</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/foxdale-village-provider-pa">Foxdale Village</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/friendship-village-of-south-hi-provider-pa">Friendship Village Of South Hi</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">G</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/gardens-at-easton-the-provider-pa">Gardens At Easton The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/gardens-for-memory-care-at-easton-the-provider-pa">Gardens For Memory Care At Easton The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/germantown-home-provider-pa">Germantown Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/gino-j-merli-veterans-center-provider-pa">Gino J Merli Veterans Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/glen-at-willow-valley-provider-pa">Glen At Willow Valley</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/good-shepherd-home-bethlehem-provider-pa">Good Shepherd Home Bethlehem</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/good-shepherd-home-raker-center-provider-pa">Good Shepherd Home Raker Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/graduate-post-acute-provider-pa">Graduate Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/green-ridge-care-center-provider-pa">Green Ridge Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/greenfield-healthcare-and-rehabilitation-center-provider-pa">Greenfield Healthcare And Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">H</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/hamilton-arms-center-provider-pa">Hamilton Arms Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/harmony-physical-rehabilitation-provider-pa">Harmony Physical Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/heinz-transitional-rehabilitation-unit-provider-pa">Heinz Transitional Rehabilitation Unit</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/heritage-care-center-provider-pa">Heritage Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/highland-hills-post-acute-provider-pa">Highland Hills Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/hilltop-healthcare-and-rehabilitation-center-provider-pa">Hilltop Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/holy-family-home-provider-pa">Holy Family Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/holy-family-manor-provider-pa">Holy Family Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/homeland-center-provider-pa">Homeland Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/homestead-village-inc-provider-pa">Homestead Village Inc</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">I</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/immaculatemarycenter-for-rehabilitation-healthcare-provider-pa">Immaculatemarycenter For Rehabilitation Healthcare</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/independence-rehab-and-nursing-provider-pa">Independence Rehab And Nursing</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/inglis-house-provider-pa">Inglis House</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/ivy-hill-post-acute-nursing-rehabilitation-llc-provider-pa">Ivy Hill Post Acute Nursing Rehabilitation Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/ivy-park-post-acute-provider-pa">Ivy Park Post Acute</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">J</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/jewel-healthcare-and-rehabilitation-center-provider-pa">Jewel Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-gl-provider-pa">John J Kane Regional Center Gl</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-mc-provider-pa">John J Kane Regional Center Mc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-ro-provider-pa">John J Kane Regional Center Ro</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-sc-provider-pa">John J Kane Regional Center Sc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/juniper-village-at-brookline-rehabilitation-and-sk-provider-pa">Juniper Village At Brookline Rehabilitation And Sk</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">K</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/kearsley-rehabilitation-and-nursing-center-provider-pa">Kearsley Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/king-of-prussia-skilled-nursing-and-rehabilitation-provider-pa">King Of Prussia Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/kingston-court-skilled-nursing-and-rehabilitation-provider-pa">Kingston Court Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/kirkland-village-provider-pa">Kirkland Village</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">L</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lafayette-redeemer-the-provider-pa">Lafayette Redeemer The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lancaster-nursing-and-rehabilitation-center-provider-pa">Lancaster Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/laurel-square-healthcare-and-rehabilitation-center-provider-pa">Laurel Square Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-asbury-ridge-dba-saint-marys-asbury-ridg-provider-pa">Lecom At Asbury Ridge Dba Saint Marys Asbury Ridg</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-elmwood-gardens-llc-provider-pa">Lecom At Elmwood Gardens Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-presque-isle-inc-provider-pa">Lecom At Presque Isle Inc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-village-square-llc-provider-pa">Lecom At Village Square Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lehigh-valley-hospital-tsu-provider-pa">Lehigh Valley Hospital Tsu</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/liberty-center-for-rehabilitation-and-nursing-provider-pa">Liberty Center For Rehabilitation And Nursing</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/linwood-nursing-and-rehabilitation-center-provider-pa">Linwood Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/little-sisters-of-the-poor-provider-pa">Little Sisters Of The Poor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/logan-square-rehabilitation-and-healthcare-center-provider-pa">Logan Square Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/luther-crest-nursing-facility-provider-pa">Luther Crest Nursing Facility</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">M</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/manchester-commons-of-presbyterian-seniorcare-provider-pa">Manchester Commons Of Presbyterian Seniorcare</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/maplewood-nursing-and-rehab-center-provider-pa">Maplewood Nursing And Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/margaret-e-moul-home-provider-pa">Margaret E Moul Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/marywood-heights-provider-pa">Marywood Heights</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/maybrook-hills-rehabilitation-and-healthcare-cente-provider-pa">Maybrook Hills Rehabilitation And Healthcare Cente</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/midtown-oaks-health-rehab-center-provider-pa">Midtown Oaks Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/millcreek-manor-provider-pa">Millcreek Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/misericordia-nursing-rehabilitation-center-provider-pa">Misericordia Nursing Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/monroeville-post-acute-provider-pa">Monroeville Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/monumentalpostacutecare-at-woodside-park-provider-pa">Monumentalpostacutecare At Woodside Park</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/moravian-village-of-bethlehem-provider-pa">Moravian Village Of Bethlehem</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">N</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/neffsville-nursing-and-rehabilitation-provider-pa">Neffsville Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/new-eastwood-healthcare-and-rehabilitation-center-provider-pa">New Eastwood Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/nightingale-nursing-and-rehab-center-provider-pa">Nightingale Nursing And Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/normandie-ridge-provider-pa">Normandie Ridge</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/northampton-post-acute-provider-pa">Northampton Post Acute</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">O</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/oakwood-healthcare-rehabilitation-center-provider-pa">Oakwood Healthcare Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">P</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pauls-run-provider-pa">Pauls Run</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pennsylvania-soldiers-and-sailors-home-provider-pa">Pennsylvania Soldiers And Sailors Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pennypack-rehab-and-care-center-provider-pa">Pennypack Rehab And Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/philadelphia-protestant-home-provider-pa">Philadelphia Protestant Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/phoebe-allentown-health-care-center-provider-pa">Phoebe Allentown Health Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pleasant-acres-rehabilitation-and-nursing-center-provider-pa">Pleasant Acres Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/providence-point-healthcare-residence-provider-pa">Providence Point Healthcare Residence</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">R</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/reformed-presbyterian-home-provider-pa">Reformed Presbyterian Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rehabilitation-center-at-brethren-village-llc-provider-pa">Rehabilitation Center At Brethren Village Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/renaissance-healthcare-rehabilitation-center-provider-pa">Renaissance Healthcare Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rest-haven-york-provider-pa">Rest Haven York</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rittenhouse-post-acute-provider-pa">Rittenhouse Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rivers-bend-health-rehab-center-provider-pa">Rivers Bend Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rivers-edge-rehabilitation-healthcare-center-provider-pa">Rivers Edge Rehabilitation Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/riverstreet-manor-provider-pa">Riverstreet Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/riverton-rehabilitation-and-healthcare-center-provider-pa">Riverton Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/roosevelt-rehabilitation-and-healthcare-center-provider-pa">Roosevelt Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rose-city-nursing-and-rehab-at-lancaster-provider-pa">Rose City Nursing And Rehab At Lancaster</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rose-meadows-health-rehab-center-provider-pa">Rose Meadows Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rose-view-rehab-and-care-center-provider-pa">Rose View Rehab And Care Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">S</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/sarah-reed-senior-living-provider-pa">Sarah Reed Senior Living</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/scranton-health-care-center-provider-pa">Scranton Health Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/simpson-house-inc-provider-pa">Simpson House Inc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/southwestern-nursing-and-rehabilitation-center-provider-pa">Southwestern Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/southwestern-veterans-center-provider-pa">Southwestern Veterans Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/spiritrust-lutheran-the-village-at-sprenkle-drive-provider-pa">Spiritrust Lutheran The Village At Sprenkle Drive</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/spring-creek-rehabilitation-and-nursing-center-provider-pa">Spring Creek Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/spring-hill-rehabilitation-and-nursing-center-provider-pa">Spring Hill Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/squirrel-hill-wellness-and-rehabilitation-center-provider-pa">Squirrel Hill Wellness And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/st-john-neumann-ctr-for-rehab-healthcare-provider-pa">St John Neumann Ctr For Rehab Healthcare</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/st-monica-center-for-rehabilitation-healthcare-provider-pa">St Monica Center For Rehabilitation Healthcare</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">T</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/the-pines-at-philadelphia-rehab-and-healthcare-ctr-provider-pa">The Pines At Philadelphia Rehab And Healthcare Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/transitional-care-unit-at-nazareth-hospital-provider-pa">Transitional Care Unit At Nazareth Hospital</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/trillium-place-provider-pa">Trillium Place</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/tucker-house-nursing-and-rehabilitation-center-provider-pa">Tucker House Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/twinbrook-healthcare-and-rehabilitation-center-provider-pa">Twinbrook Healthcare And Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">U</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/university-city-rehabilitation-and-healthcare-ctr-provider-pa">University City Rehabilitation And Healthcare Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/upmc-magee-womens-hospital-tcu-provider-pa">Upmc Magee Womens Hospital Tcu</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">V</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/village-at-penn-state-the-provider-pa">Village At Penn State The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/vincentian-home-provider-pa">Vincentian Home</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">W</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/walnut-creek-nursing-and-rehab-provider-pa">Walnut Creek Nursing And Rehab</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wecare-at-monroeville-rehabilitation-and-nsg-ctr-provider-pa">Wecare At Monroeville Rehabilitation And Nsg Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wecare-at-mt-lebanon-rehabilitation-and-nrsg-ctr-provider-pa">Wecare At Mt Lebanon Rehabilitation And Nrsg Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wesley-enhanced-living-at-stapeley-provider-pa">Wesley Enhanced Living At Stapeley</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wesley-enhanced-living-pennypack-park-provider-pa">Wesley Enhanced Living Pennypack Park</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/west-park-rehabilitation-and-nursing-center-provider-pa">West Park Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/whitehall-borough-post-acute-provider-pa">Whitehall Borough Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/williamsport-home-the-provider-pa">Williamsport Home The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/willow-terrace-provider-pa">Willow Terrace</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/willowcrest-provider-pa">Willowcrest</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/woodhaven-health-rehab-center-provider-pa">Woodhaven Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wyomissing-health-and-rehabilitation-center-provider-pa">Wyomissing Health And Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">Y</div>
          <div class="rsa-ix-alpha-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/york-north-skilled-nursing-and-rehabilitation-ctr-provider-pa">York North Skilled Nursing And Rehabilitation Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/york-nursing-and-rehabilitation-center-provider-pa">York Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/york-south-skilled-nursing-and-rehabilitation-ctr-provider-pa">York South Skilled Nursing And Rehabilitation Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/yorkview-nursing-and-rehabilitation-provider-pa">Yorkview Nursing And Rehabilitation</a></div></div>
        </div>

  <div class="rsa-ix-related">
    <a href="https://www.restingsycamore.com/medicare/providers">← All States</a>
    <a href="https://www.restingsycamore.com/medicare/states/pennsylvania">Medicare in Pennsylvania</a>
    <a href="https://www.restingsycamore.com/medicare/doctors/pennsylvania">Pennsylvania Doctors</a>
    <a href="https://www.restingsycamore.com/medicare/plans/pennsylvania">Pennsylvania Plans</a>
  </div>

  
  
</div></div>`;
})();
