(function(){
  var el = document.getElementById('rsa-providers-pa');
  if (!el) return;
  if (!document.getElementById('rsa-ix-styles')) {
    var s = document.createElement('style');
    s.id = 'rsa-ix-styles';
    s.textContent = `.rsa-ix-wrap{font-family:"Onest",system-ui,sans-serif;color:#1e293b;box-sizing:border-box}
.rsa-ix-wrap *{box-sizing:border-box}
.rsa-ix-header{background:#1e3a5f;color:#fff;padding:32px 40px}
.rsa-ix-header h1{font-size:1.9rem;font-weight:800;margin-bottom:8px;line-height:1.2}
.rsa-ix-header p{color:#94a3b8;font-size:0.95rem;max-width:600px;line-height:1.6}
.rsa-ix-container{max-width:1100px;margin:0 auto;padding:36px 40px}
.rsa-ix-intro{background:#f8fafc;border-left:4px solid #2563eb;padding:16px 20px;border-radius:0 8px 8px 0;margin-bottom:32px;font-size:0.95rem;line-height:1.7;color:#334155}
.rsa-ix-section-title{font-size:0.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin-bottom:12px;margin-top:32px;border-bottom:1px solid #e2e8f0;padding-bottom:8px}
.rsa-ix-letter-heading{font-size:1.4rem;font-weight:800;color:#0f172a;margin-bottom:10px}
.rsa-ix-letter-group{margin-bottom:24px}
.rsa-ix-link-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:6px}
.rsa-ix-link-item a{display:block;padding:7px 12px;border-radius:6px;text-decoration:none;color:#1e40af;font-size:0.875rem;transition:background .1s;border:1px solid transparent}
.rsa-ix-link-item a:hover{background:#eff6ff;border-color:#bfdbfe}
.rsa-ix-link-item .sub{font-size:0.75rem;color:#94a3b8;margin-top:1px}
.rsa-ix-state-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:18px;margin-bottom:36px}
.rsa-ix-state-card{border:1px solid #e2e8f0;border-radius:10px;padding:22px;text-decoration:none;color:inherit;display:block;transition:box-shadow .15s}
.rsa-ix-state-card:hover{box-shadow:0 4px 16px rgba(0,0,0,.1);border-color:#2563eb}
.rsa-ix-state-card .count{font-size:2.3rem;font-weight:800;color:#2563eb;line-height:1}
.rsa-ix-state-card .label{font-size:0.95rem;font-weight:600;margin-top:6px}
.rsa-ix-state-card .sub{font-size:0.8rem;color:#64748b;margin-top:4px}
.rsa-ix-stats-bar{display:flex;gap:24px;margin-bottom:24px;flex-wrap:wrap}
.rsa-ix-stat .num{font-size:1.7rem;font-weight:800;color:#0f172a}
.rsa-ix-stat .lbl{font-size:0.75rem;color:#64748b;text-transform:uppercase;letter-spacing:.04em}
.rsa-ix-table{width:100%;border-collapse:collapse;font-size:0.875rem}
.rsa-ix-table th{text-align:left;padding:10px 14px;background:#f8fafc;font-size:0.75rem;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#475569;border-bottom:2px solid #e2e8f0}
.rsa-ix-table td{padding:9px 14px;border-bottom:1px solid #f1f5f9}
.rsa-ix-table tr:hover td{background:#f8fafc}
.rsa-ix-pills{display:flex;flex-wrap:wrap;gap:6px}
.rsa-ix-pill a{display:inline-block;padding:3px 10px;background:#eff6ff;color:#1d4ed8;border-radius:999px;font-size:0.78rem;text-decoration:none;font-weight:500}
.rsa-ix-pill a:hover{background:#dbeafe}
.rsa-ix-related{display:flex;gap:10px;flex-wrap:wrap;margin-top:36px;padding-top:22px;border-top:1px solid #e2e8f0}
.rsa-ix-related a{padding:7px 14px;border:1px solid #e2e8f0;border-radius:6px;text-decoration:none;color:#475569;font-size:0.85rem}
.rsa-ix-related a:hover{border-color:#2563eb;color:#2563eb}
.rsa-ix-card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:18px;margin-bottom:32px}
.rsa-ix-card{border:1px solid #e2e8f0;border-radius:10px;padding:22px;text-decoration:none;color:inherit;display:block;transition:box-shadow .15s}
.rsa-ix-card:hover{box-shadow:0 4px 16px rgba(0,0,0,.1);border-color:#2563eb}
.rsa-ix-card h3{font-size:1.05rem;font-weight:700;color:#0f172a;margin-bottom:6px}
.rsa-ix-card p{font-size:0.85rem;color:#64748b;line-height:1.5}
.rsa-ix-tag{display:inline-block;padding:2px 8px;background:#f0fdf4;color:#166534;border-radius:4px;font-size:0.75rem;font-weight:600;margin-top:8px}
.rsa-ix-faq-item{border:1px solid #e2e8f0;border-radius:8px;padding:20px 24px;margin-bottom:12px}
.rsa-ix-faq-item h3{font-size:0.95rem;font-weight:700;color:#0f172a;margin-bottom:8px}
.rsa-ix-faq-item p{font-size:0.875rem;color:#334155;line-height:1.65}
.rsa-ix-faq-item a{color:#2563eb;text-decoration:none}
.rsa-ix-faq-item a:hover{text-decoration:underline}
.rsa-ix-toc{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:20px 24px;margin-bottom:32px}
.rsa-ix-toc h2{font-size:0.85rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#64748b;margin-bottom:12px}
.rsa-ix-toc ul{list-style:none;display:flex;flex-wrap:wrap;gap:8px}
.rsa-ix-toc li a{padding:5px 12px;background:#fff;border:1px solid #e2e8f0;border-radius:6px;text-decoration:none;color:#2563eb;font-size:0.85rem}
.rsa-ix-toc li a:hover{border-color:#2563eb}
.rsa-ix-plan-card{border:1px solid #e2e8f0;border-radius:10px;padding:22px;margin-bottom:14px;display:flex;align-items:flex-start;gap:16px;text-decoration:none;color:inherit;transition:box-shadow .15s}
.rsa-ix-plan-card:hover{box-shadow:0 4px 16px rgba(0,0,0,.1);border-color:#2563eb}
.rsa-ix-plan-card .badge{display:inline-block;padding:3px 10px;border-radius:4px;font-size:0.75rem;font-weight:600;background:#dbeafe;color:#1e40af}
.rsa-ix-article-list{list-style:none}
.rsa-ix-article-item{border-bottom:1px solid #e2e8f0;padding:16px 0}
.rsa-ix-article-item:last-child{border-bottom:none}
.rsa-ix-article-item a{font-size:0.95rem;font-weight:600;color:#1e40af;text-decoration:none}
.rsa-ix-article-item a:hover{text-decoration:underline}
.rsa-ix-article-item .meta{font-size:0.8rem;color:#64748b;margin-top:4px}
.rsa-ix-cta{background:#1e3a5f;color:#fff;border-radius:10px;padding:28px 32px;margin-top:36px;text-align:center}
.rsa-ix-cta h2{font-size:1.2rem;font-weight:700;margin-bottom:8px}
.rsa-ix-cta p{font-size:0.9rem;color:#94a3b8;margin-bottom:16px}
.rsa-ix-cta a{display:inline-block;background:#2563eb;color:#fff;padding:10px 24px;border-radius:6px;text-decoration:none;font-weight:600;font-size:0.9rem}
.rsa-ix-cta a:hover{background:#1d4ed8}
@media(max-width:640px){
  .rsa-ix-header{padding:24px 20px}
  .rsa-ix-container{padding:24px 20px}
  .rsa-ix-stats-bar{gap:16px}
  .rsa-ix-state-cards,.rsa-ix-card-grid{grid-template-columns:1fr}
}
.rsa-ix-hero{background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%);color:white;padding:48px 24px 40px;margin:-8px -8px 0}
.rsa-ix-hero h1{font-family:"Onest",system-ui,sans-serif;font-size:clamp(24px,4vw,36px);font-weight:700;margin:12px 0 8px;letter-spacing:-0.3px}
.rsa-ix-hero p{font-size:16px;opacity:0.85;max-width:600px;line-height:1.6;margin:0}
.rsa-ix-breadcrumb{font-size:13px;opacity:0.75;margin-bottom:8px}
.rsa-ix-breadcrumb a{color:white;text-decoration:none}
.rsa-ix-breadcrumb a:hover{text-decoration:underline}
.rsa-ix-breadcrumb span{margin:0 4px}
.rsa-ix-bc-current{opacity:0.9}`;
    document.head.appendChild(s);
  }
  el.innerHTML = `<div class="rsa-ix-wrap"><div class="rsa-ix-hero"><div class="rsa-ix-breadcrumb"><a href="https://www.restingsycamore.com">Home</a> <span>›</span> <a href="https://www.restingsycamore.com/medicare">Medicare</a> <span>›</span> <a href="https://www.restingsycamore.com/medicare/providers">Providers</a> <span>›</span> <span class="rsa-ix-bc-current">Pennsylvania</span></div><h1>Medicare Care Facilities in Pennsylvania</h1><p>167 Medicare-certified skilled nursing and care facilities in Pennsylvania.</p></div><div class="rsa-ix-container">
  <div class="rsa-ix-stats-bar">
    <div class="stat"><div class="num">167</div><div class="lbl">Facilities</div></div>
  </div>

  <div class="rsa-ix-intro">
    Medicare Part A covers up to 100 days in a skilled nursing facility after a qualifying hospital stay —
    but only at Medicare-certified facilities. These 167 Pennsylvania facilities are Medicare-certified.
    Click any facility to view coverage details, accepted plans, and location information.
  </div>

  <div class="rsa-ix-section-title">All Pennsylvania Medicare Care Facilities — A to Z</div>
  
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">A</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/abbeyville-skilled-nursing-and-rehabilitation-cent-provider-pa">Abbeyville Skilled Nursing And Rehabilitation Cent</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/accela-rehab-and-care-center-at-somerton-provider-pa">Accela Rehab And Care Center At Somerton</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/advanced-health-care-of-hanover-provider-pa">Advanced Health Care Of Hanover</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/allied-services-skilled-nursing-center-provider-pa">Allied Services Skilled Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/allied-services-transitional-rehab-unit-provider-pa">Allied Services Transitional Rehab Unit</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/amoroso-healthcare-and-rehabilitation-woodridge-provider-pa">Amoroso Healthcare And Rehabilitation Woodridge</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/aristacare-at-east-falls-provider-pa">Aristacare At East Falls</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/asbury-health-center-provider-pa">Asbury Health Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">B</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/ball-pavilion-the-provider-pa">Ball Pavilion The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/belvedere-center-genesis-healthcare-the-provider-pa">Belvedere Center Genesis Healthcare The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/bethlehem-north-skilled-nursing-and-rehabilitation-provider-pa">Bethlehem North Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/bethlehem-south-skilled-nursing-and-rehabilitation-provider-pa">Bethlehem South Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/brethren-village-provider-pa">Brethren Village</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/burgh-care-center-provider-pa">Burgh Care Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">C</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/canterbury-place-provider-pa">Canterbury Place</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/capitol-rehabilitation-and-healthcare-center-provider-pa">Capitol Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/care-pavilion-nursing-and-rehabilitation-center-provider-pa">Care Pavilion Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/caring-heart-rehabilitation-and-nursing-center-provider-pa">Caring Heart Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/carnegie-park-post-acute-provider-pa">Carnegie Park Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cathedral-village-provider-pa">Cathedral Village</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cedar-crest-post-acute-provider-pa">Cedar Crest Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cedarbrook-senior-care-and-rehabilitation-provider-pa">Cedarbrook Senior Care And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/centennial-healthcare-and-rehabilitation-center-provider-pa">Centennial Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/chapel-manor-provider-pa">Chapel Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/cliveden-nursing-and-rehabilitation-center-provider-pa">Cliveden Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/complete-care-at-berkshire-llc-provider-pa">Complete Care At Berkshire Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/concordia-at-the-cedars-provider-pa">Concordia At The Cedars</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/concordia-of-the-south-hills-provider-pa">Concordia Of The South Hills</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/corner-view-nursing-and-rehabilitation-center-provider-pa">Corner View Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/country-meadows-nursing-center-of-bethlehem-provider-pa">Country Meadows Nursing Center Of Bethlehem</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">D</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/deer-meadows-rehabilitation-center-provider-pa">Deer Meadows Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/delaware-valley-veterans-home-provider-pa">Delaware Valley Veterans Home</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">E</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/east-end-health-rehab-center-provider-pa">East End Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/easton-skilled-nursing-and-rehabilitation-center-provider-pa">Easton Skilled Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/edenbrook-north-provider-pa">Edenbrook North</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/edenbrook-south-provider-pa">Edenbrook South</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/elan-skilled-nursing-and-rehab-a-jewish-senior-li-provider-pa">Elan Skilled Nursing And Rehab A Jewish Senior Li</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/embassy-of-east-mountain-provider-pa">Embassy Of East Mountain</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/embassy-of-hearthside-provider-pa">Embassy Of Hearthside</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/embassy-of-scranton-provider-pa">Embassy Of Scranton</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">F</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/fairlane-gardens-nursing-and-rehab-at-reading-provider-pa">Fairlane Gardens Nursing And Rehab At Reading</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/fairview-rehab-and-care-center-provider-pa">Fairview Rehab And Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/forestview-provider-pa">Forestview</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/fox-subacute-at-south-philadelphia-provider-pa">Fox Subacute At South Philadelphia</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/foxdale-village-provider-pa">Foxdale Village</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/friendship-village-of-south-hi-provider-pa">Friendship Village Of South Hi</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">G</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/gardens-at-easton-the-provider-pa">Gardens At Easton The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/gardens-for-memory-care-at-easton-the-provider-pa">Gardens For Memory Care At Easton The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/germantown-home-provider-pa">Germantown Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/gino-j-merli-veterans-center-provider-pa">Gino J Merli Veterans Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/glen-at-willow-valley-provider-pa">Glen At Willow Valley</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/good-shepherd-home-bethlehem-provider-pa">Good Shepherd Home Bethlehem</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/good-shepherd-home-raker-center-provider-pa">Good Shepherd Home Raker Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/graduate-post-acute-provider-pa">Graduate Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/green-ridge-care-center-provider-pa">Green Ridge Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/greenfield-healthcare-and-rehabilitation-center-provider-pa">Greenfield Healthcare And Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">H</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/hamilton-arms-center-provider-pa">Hamilton Arms Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/harmony-physical-rehabilitation-provider-pa">Harmony Physical Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/heinz-transitional-rehabilitation-unit-provider-pa">Heinz Transitional Rehabilitation Unit</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/heritage-care-center-provider-pa">Heritage Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/highland-hills-post-acute-provider-pa">Highland Hills Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/hilltop-healthcare-and-rehabilitation-center-provider-pa">Hilltop Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/holy-family-home-provider-pa">Holy Family Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/holy-family-manor-provider-pa">Holy Family Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/homeland-center-provider-pa">Homeland Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/homestead-village-inc-provider-pa">Homestead Village Inc</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">I</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/immaculatemarycenter-for-rehabilitation-healthcare-provider-pa">Immaculatemarycenter For Rehabilitation Healthcare</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/independence-rehab-and-nursing-provider-pa">Independence Rehab And Nursing</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/inglis-house-provider-pa">Inglis House</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/ivy-hill-post-acute-nursing-rehabilitation-llc-provider-pa">Ivy Hill Post Acute Nursing Rehabilitation Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/ivy-park-post-acute-provider-pa">Ivy Park Post Acute</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">J</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/jewel-healthcare-and-rehabilitation-center-provider-pa">Jewel Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-gl-provider-pa">John J Kane Regional Center Gl</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-mc-provider-pa">John J Kane Regional Center Mc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-ro-provider-pa">John J Kane Regional Center Ro</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/john-j-kane-regional-center-sc-provider-pa">John J Kane Regional Center Sc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/juniper-village-at-brookline-rehabilitation-and-sk-provider-pa">Juniper Village At Brookline Rehabilitation And Sk</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">K</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/kearsley-rehabilitation-and-nursing-center-provider-pa">Kearsley Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/king-of-prussia-skilled-nursing-and-rehabilitation-provider-pa">King Of Prussia Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/kingston-court-skilled-nursing-and-rehabilitation-provider-pa">Kingston Court Skilled Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/kirkland-village-provider-pa">Kirkland Village</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">L</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lafayette-redeemer-the-provider-pa">Lafayette Redeemer The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lancaster-nursing-and-rehabilitation-center-provider-pa">Lancaster Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/laurel-square-healthcare-and-rehabilitation-center-provider-pa">Laurel Square Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-asbury-ridge-dba-saint-marys-asbury-ridg-provider-pa">Lecom At Asbury Ridge Dba Saint Marys Asbury Ridg</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-elmwood-gardens-llc-provider-pa">Lecom At Elmwood Gardens Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-presque-isle-inc-provider-pa">Lecom At Presque Isle Inc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lecom-at-village-square-llc-provider-pa">Lecom At Village Square Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/lehigh-valley-hospital-tsu-provider-pa">Lehigh Valley Hospital Tsu</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/liberty-center-for-rehabilitation-and-nursing-provider-pa">Liberty Center For Rehabilitation And Nursing</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/linwood-nursing-and-rehabilitation-center-provider-pa">Linwood Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/little-sisters-of-the-poor-provider-pa">Little Sisters Of The Poor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/logan-square-rehabilitation-and-healthcare-center-provider-pa">Logan Square Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/luther-crest-nursing-facility-provider-pa">Luther Crest Nursing Facility</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">M</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/manchester-commons-of-presbyterian-seniorcare-provider-pa">Manchester Commons Of Presbyterian Seniorcare</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/maplewood-nursing-and-rehab-center-provider-pa">Maplewood Nursing And Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/margaret-e-moul-home-provider-pa">Margaret E Moul Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/marywood-heights-provider-pa">Marywood Heights</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/maybrook-hills-rehabilitation-and-healthcare-cente-provider-pa">Maybrook Hills Rehabilitation And Healthcare Cente</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/midtown-oaks-health-rehab-center-provider-pa">Midtown Oaks Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/millcreek-manor-provider-pa">Millcreek Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/misericordia-nursing-rehabilitation-center-provider-pa">Misericordia Nursing Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/monroeville-post-acute-provider-pa">Monroeville Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/monumentalpostacutecare-at-woodside-park-provider-pa">Monumentalpostacutecare At Woodside Park</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/moravian-village-of-bethlehem-provider-pa">Moravian Village Of Bethlehem</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">N</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/neffsville-nursing-and-rehabilitation-provider-pa">Neffsville Nursing And Rehabilitation</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/new-eastwood-healthcare-and-rehabilitation-center-provider-pa">New Eastwood Healthcare And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/nightingale-nursing-and-rehab-center-provider-pa">Nightingale Nursing And Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/normandie-ridge-provider-pa">Normandie Ridge</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/northampton-post-acute-provider-pa">Northampton Post Acute</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">O</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/oakwood-healthcare-rehabilitation-center-provider-pa">Oakwood Healthcare Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">P</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pauls-run-provider-pa">Pauls Run</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pennsylvania-soldiers-and-sailors-home-provider-pa">Pennsylvania Soldiers And Sailors Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pennypack-rehab-and-care-center-provider-pa">Pennypack Rehab And Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/philadelphia-protestant-home-provider-pa">Philadelphia Protestant Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/phoebe-allentown-health-care-center-provider-pa">Phoebe Allentown Health Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/pleasant-acres-rehabilitation-and-nursing-center-provider-pa">Pleasant Acres Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/providence-point-healthcare-residence-provider-pa">Providence Point Healthcare Residence</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">R</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/reformed-presbyterian-home-provider-pa">Reformed Presbyterian Home</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rehabilitation-center-at-brethren-village-llc-provider-pa">Rehabilitation Center At Brethren Village Llc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/renaissance-healthcare-rehabilitation-center-provider-pa">Renaissance Healthcare Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rest-haven-york-provider-pa">Rest Haven York</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rittenhouse-post-acute-provider-pa">Rittenhouse Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rivers-bend-health-rehab-center-provider-pa">Rivers Bend Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rivers-edge-rehabilitation-healthcare-center-provider-pa">Rivers Edge Rehabilitation Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/riverstreet-manor-provider-pa">Riverstreet Manor</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/riverton-rehabilitation-and-healthcare-center-provider-pa">Riverton Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/roosevelt-rehabilitation-and-healthcare-center-provider-pa">Roosevelt Rehabilitation And Healthcare Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rose-city-nursing-and-rehab-at-lancaster-provider-pa">Rose City Nursing And Rehab At Lancaster</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rose-meadows-health-rehab-center-provider-pa">Rose Meadows Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/rose-view-rehab-and-care-center-provider-pa">Rose View Rehab And Care Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">S</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/sarah-reed-senior-living-provider-pa">Sarah Reed Senior Living</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/scranton-health-care-center-provider-pa">Scranton Health Care Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/simpson-house-inc-provider-pa">Simpson House Inc</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/southwestern-nursing-and-rehabilitation-center-provider-pa">Southwestern Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/southwestern-veterans-center-provider-pa">Southwestern Veterans Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/spiritrust-lutheran-the-village-at-sprenkle-drive-provider-pa">Spiritrust Lutheran The Village At Sprenkle Drive</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/spring-creek-rehabilitation-and-nursing-center-provider-pa">Spring Creek Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/spring-hill-rehabilitation-and-nursing-center-provider-pa">Spring Hill Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/squirrel-hill-wellness-and-rehabilitation-center-provider-pa">Squirrel Hill Wellness And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/st-john-neumann-ctr-for-rehab-healthcare-provider-pa">St John Neumann Ctr For Rehab Healthcare</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/st-monica-center-for-rehabilitation-healthcare-provider-pa">St Monica Center For Rehabilitation Healthcare</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">T</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/the-pines-at-philadelphia-rehab-and-healthcare-ctr-provider-pa">The Pines At Philadelphia Rehab And Healthcare Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/transitional-care-unit-at-nazareth-hospital-provider-pa">Transitional Care Unit At Nazareth Hospital</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/trillium-place-provider-pa">Trillium Place</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/tucker-house-nursing-and-rehabilitation-center-provider-pa">Tucker House Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/twinbrook-healthcare-and-rehabilitation-center-provider-pa">Twinbrook Healthcare And Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">U</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/university-city-rehabilitation-and-healthcare-ctr-provider-pa">University City Rehabilitation And Healthcare Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/upmc-magee-womens-hospital-tcu-provider-pa">Upmc Magee Womens Hospital Tcu</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">V</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/village-at-penn-state-the-provider-pa">Village At Penn State The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/vincentian-home-provider-pa">Vincentian Home</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">W</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/walnut-creek-nursing-and-rehab-provider-pa">Walnut Creek Nursing And Rehab</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wecare-at-monroeville-rehabilitation-and-nsg-ctr-provider-pa">Wecare At Monroeville Rehabilitation And Nsg Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wecare-at-mt-lebanon-rehabilitation-and-nrsg-ctr-provider-pa">Wecare At Mt Lebanon Rehabilitation And Nrsg Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wesley-enhanced-living-at-stapeley-provider-pa">Wesley Enhanced Living At Stapeley</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wesley-enhanced-living-pennypack-park-provider-pa">Wesley Enhanced Living Pennypack Park</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/west-park-rehabilitation-and-nursing-center-provider-pa">West Park Rehabilitation And Nursing Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/whitehall-borough-post-acute-provider-pa">Whitehall Borough Post Acute</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/williamsport-home-the-provider-pa">Williamsport Home The</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/willow-terrace-provider-pa">Willow Terrace</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/willowcrest-provider-pa">Willowcrest</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/woodhaven-health-rehab-center-provider-pa">Woodhaven Health Rehab Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/wyomissing-health-and-rehabilitation-center-provider-pa">Wyomissing Health And Rehabilitation Center</a></div></div>
        </div>
        <div class="rsa-ix-letter-group">
          <div class="rsa-ix-letter-heading">Y</div>
          <div class="rsa-ix-link-grid"><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/york-north-skilled-nursing-and-rehabilitation-ctr-provider-pa">York North Skilled Nursing And Rehabilitation Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/york-nursing-and-rehabilitation-center-provider-pa">York Nursing And Rehabilitation Center</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/york-south-skilled-nursing-and-rehabilitation-ctr-provider-pa">York South Skilled Nursing And Rehabilitation Ctr</a></div><div class="rsa-ix-link-item"><a href="https://www.restingsycamore.com/medicare/providers/yorkview-nursing-and-rehabilitation-provider-pa">Yorkview Nursing And Rehabilitation</a></div></div>
        </div>

  <div class="rsa-ix-related">
    <a href="https://www.restingsycamore.com/medicare/providers">← All States</a>
    <a href="https://www.restingsycamore.com/medicare/states/pennsylvania">Medicare in Pennsylvania</a>
    <a href="https://www.restingsycamore.com/medicare/doctors/pennsylvania">Pennsylvania Doctors</a>
    <a href="https://www.restingsycamore.com/medicare/plans/pennsylvania">Pennsylvania Plans</a>
  </div>

  
  
</div></div>`;
})();
